FROM ruby:2.6.6
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

RUN mkdir /indigo-league-api
WORKDIR /indigo-league-api

COPY Gemfile .
COPY Gemfile.lock .

RUN gem install bundler -v 2.1.4
RUN bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java
RUN bundle install

COPY . /indigo-league-api

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]