version: "3.9"
services:
  indigo-league-db:
    image: postgres:13
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/indigo-league-api
    # environment:
    #   DATABASE_HOST: indigo-league-db
    #   DATABASE_USER: brendenthornton
    #   DATABASE_PASSWORD: testpass
    #   DATABASE_NAME: indigo_development
    #   DATABASE_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - indigo-league-db
