---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/create":
    post:
      summary: Creates a new League
      tags:
      - Leagues
      parameters: []
      responses:
        '200':
          description: Successfully create a new League
          content: {}
        '401':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/sign_up":
    post:
      summary: Creates a new Trainer profile
      tags:
      - Trainers
      parameters: []
      responses:
        '200':
          description: Successfull Registration
          content: {}
        '401':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/login":
    post:
      summary: Logs in a Trainer
      tags:
      - Trainers
      parameters: []
      responses:
        '200':
          description: Successful Login
          content: {}
        '401':
          description: invalid request
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
